[project]
name = "Splitter"
version = "4.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "pyside6>=6.10.1",
    "scipy>=1.16.3",
    "vispy>=0.16.0",
]
